name: fd-cpr
description: Firefighter Down: CPR
extendedDescription: When the unthinkable happens and a firefighter collapses while in full turnout gear, we need a means of rapidly extricating them from this gear. FD-CPR provides a simple training method which can be used to meet this goal.
url: http://fd-cpr.com
